spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: libraryMongo

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
  info:
    git:
      mode: full
  cors:
    allowed-origins: http://localhost:9090/
    allowed-methods: GET,POST,OPTIONS

hystrix:
  dashboard:
    proxy-stream-allow-list: "*"

logging:
  file:
    name: my.log