library:
  locale: ru

spring:
  main:
    allow-circular-references: true

  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

  batch:
    job:
      enabled: false

    shell:
      interactive:
        enabled: true

  mongodb:
    embedded:
      version: 3.4.0

  data:
    mongodb:
      host: localhost
      port: 27017
      database: libraryMongo

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

    show-sql: true

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

logging:
  level:
    ROOT: INFO