drop table if exists books cascade;
drop table if exists authors cascade;
drop table if exists commentaries cascade;
drop table if exists genres cascade;
create table authors (id bigint generated by default as identity,
                      first_name varchar(255) not null,
                      last_name varchar(255) not null,
                      primary key (id));
create table genres (id bigint generated by default as identity,
                     name varchar(255) not null,
                     primary key (id));
create table books (id bigint generated by default as identity,
                    name varchar(255) not null,
                    author_id bigint references authors(id) on delete cascade,
                    genre_id bigint references genres(id) on delete cascade,
                    primary key (id));
create table commentaries (id bigint generated by default as identity,
                           text varchar(255) not null,
                           book_id bigint references books(id) on delete cascade,
                           primary key (id));