spring:
  application:
    name: payment_service
  cloud:
    config:
      enabled: false
  data:
    mongodb:
      uri: mongodb+srv://user:qwerty123@cluster0.vbyd5.mongodb.net/paymentsDB?retryWrites=true&w=majority
      database: paymentsDB

server:
  port: 9201

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

logging:
  file:
    name: payment_service.log

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  server:
    eviction-interval-timer-in-ms: 15000
  instance:
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
