version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
    ports:
      - "8080:8080"
    networks:
      - nw
  mongodb:
    image: "mongo:5"
    ports:
      - "27017:27017"
    networks:
      - nw
networks:
  nw: